### ISSUE TITLE
我为什么用这个sample没法完成更新呢？

### ISSUE THREAD

**Issue by zhuxiangqing** [TinkerPatch/tinkerpatch-flavors-sample#2]
我在使用TinkerPatch的时候，首先参考了tinkerpatch-sample fork之后，从打包到更新补丁 测试成功；
但是在应用于我自己的项目的时候始终不能实现更新（我的多个项目，都使用到了Flavors,他们有不同的资源文件），我参照本项目针对Flavors部分的配置配置了自己的项目，仍然不能实现更新。

在这之后，我fork了本仓库，运行了本项目，修改APPKEY 打了flavor1的包，修改了ActionBar的Title，增加了一个TextView（这些是我对thinkerpatch-sample做的相同的步骤)，更新没有成功。没有应用，没有下载数。这是为什么？

在上述流程中：始终使用的相同的环境（包括AndroidStudio,Gradle，Huawei API19的手机，相同的数据线，还有写代码的我，等）

**Comment by simpleton** [comment]
麻烦贴一下错误的log，只描述现象不太方便帮你debug。看log的时候请关闭过滤器，然后只过滤tinker

**Comment by zhuxiangqing** [comment]
好的 一会儿的 
请先允许我把新现象描述完  我删除了项目中的 tinkerpatch.gradle 中的productFlavors的配置，以及build.gradle中的productFlavors的配置 简而言之就是去掉了flavors;

此时再对本项目进行相同的打补丁测试操作 ，它好用了。
描述现象是为了便于模拟，我这两次生成补丁patch 都是使用的 app->Tasks->tinker->tinkerPatchRelease

**Comment by zhuxiangqing** [comment]
Wow,发现问题了 不是项目的问题 是我发布版本的时候使用的定义的appVersion的问题 我没有注意到favor中的：` appVersion = "${tinkerpatchSupport.appVersion}_${flavorName}"`  而使用的仍然是上面定义的
`  appVersion = "1.0.0"` 刚刚debug的时候 看到请求路径上面是 :1.0.0_flavor1 这个样子的 才发觉不对

**Comment by simpleton** [comment]
@zhuxiangqing ok, 我这里在文档里强调下。这里我先关闭了
